bezier = easeOut, 0, 0, 0.2, 1
animation = global, 1, 2, easeOut
animation = inputFieldColors, 0

background {
	monitor =
	color = rgb(30, 30, 46)
}

input-field {
    monitor =
    outline_thickness = 1
    size = 320, 48
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgb(137, 180, 250)
    check_color = rgb(249, 226, 175)
    fail_color = rgb(243, 139, 168)

    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    rounding = 1920

    placeholder_text = Input Password... # remove default italicization
    font_family = Rubik

    halign = center
    valign = center
}
